# Generated by Django 4.0.4 on 2022-05-20 23:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 23, 38, 6, 898991, tzinfo=utc)),
        ),
    ]
